name: ✨ Feature Request
description: Suggest a new feature or enhancement for GitScribe
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
projects: ["GitScribe Development"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - "CLI (git-scribe command)"
        - "Desktop GUI Application"
        - "Markdown Editor"
        - "File Management"
        - "GitHub Integration"
        - "Build System"
        - "Plugin System"
        - "Theme System"
        - "Deployment"
        - "Configuration"
        - "Documentation"
        - "New Component"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "🔴 High - Essential for my workflow"
        - "🟡 Medium - Would be very helpful"
        - "🟢 Low - Nice to have"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: "Describe the problem or limitation you're experiencing..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "Describe your proposed solution..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Describe any alternative solutions you've considered..."

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial
      placeholder: |
        1. Use case 1: ...
        2. Use case 2: ...
        3. Use case 3: ...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, provide mockups, screenshots, or examples of similar features
      placeholder: "Attach mockups, screenshots, or describe examples..."

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity (if known)
      description: How complex do you think this feature would be to implement?
      options:
        - "⚡ Simple - Minor change or addition"
        - "🟡 Medium - Moderate development effort"
        - "🔴 Complex - Significant development effort"
        - "🚨 Major - Requires architectural changes"
        - "❓ Unknown - Not sure about complexity"

  - type: checkboxes
    id: related_tasks
    attributes:
      label: Related to Project Tasks
      description: Is this feature related to any existing tasks in project-tasks.md?
      options:
        - label: "This feature is related to existing project tasks"
        - label: "This is a completely new feature not covered in current tasks"
        - label: "This could be implemented as a plugin"
        - label: "This requires changes to the core architecture"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or information about the feature request

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: "I have searched existing issues to ensure this is not a duplicate"
          required: true
        - label: "I have reviewed the project requirements and tasks to see if this is already planned"
          required: true
        - label: "I understand this is a feature request and not a bug report"
          required: true 